# Generated by Django 5.0.6 on 2026-09-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_projectactivitylog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_supplementary',
            field=models.BooleanField(default=False, verbose_name='Is Supplementary Project'),
        ),
    ]
