# Generated by Django 5.0.6 on 2026-09-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_project_is_supplementary'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='default_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Default percentage calculated against actual contract amount (e.g. 10.00 for 10%)', max_digits=5, verbose_name='Default Percentage (%)'),
        ),
    ]
