# Generated by Django 5.0.6 on 2026-09-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_remove_project_rolled_over_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(verbose_name='Project Name'),
        ),
    ]
