# Generated by Django 5.0.6 on 2026-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0007_alter_company_director_name'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='companycompliance',
            index=models.Index(fields=['year', 'status'], name='contractors_year_61ca60_idx'),
        ),
        migrations.AddIndex(
            model_name='companycompliance',
            index=models.Index(fields=['company', 'year'], name='contractors_company_06a6f0_idx'),
        ),
    ]
